// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image8 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 93);
    lv_obj_set_y(ui_Label1, -229);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Disconnect");

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_606313477);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image1, 149);
    lv_obj_set_y(ui_Image1, -229);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_circle_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image2, 149);
    lv_obj_set_y(ui_Image2, -229);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 300);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_142742671);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, 15);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_851834463);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, 15);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image9, &ui_img_pumpkin_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image9, 85);
    lv_obj_set_y(ui_Image9, -155);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image11, &ui_img_pumpkin_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image11, 96);
    lv_obj_set_y(ui_Image11, 139);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image10, &ui_img_pumpkin_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image10, -104);
    lv_obj_set_y(ui_Image10, 162);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image8, &ui_img_pumpkin_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image8, -97);
    lv_obj_set_y(ui_Image8, -117);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image9 = NULL;
    ui_Image11 = NULL;
    ui_Image10 = NULL;
    ui_Image8 = NULL;

}
